### ISSUE TITLE
Some obsids are long

### ISSUE THREAD

**Issue by jeanconn** [sot/aca_preview#12]
This looks like it is a small problem on the Matlab side
```
Obsid 21826.199999999997 at 2019:039:04:05:28.402
```
because that is the value of the string key in the pickle (in FEB0419 early products) and not a formatting issue in aca_preview.

But, I think the only impact is it looking silly.

**Comment by taldcroft** [comment]
This was fixed in one of the PRs.

**Comment by jeanconn** [comment]
I think it is still a problem on the matlab side to some extent but probably not worth keeping the issue open here or in proseco issues.
